# Generated by Django 5.0.1 on 2024-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
